apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-website
  labels:
    app: nextjs-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nextjs-website
  template:
    metadata:
      labels:
        app: nextjs-website
    spec:
      containers:
        - name: nextjs-website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
