apiVersion: v1
kind: Service
metadata:
  name: nextjs-website
  labels:
    app: nextjs-website
spec:
  type: ClusterIP  # Change to LoadBalancer if external access is required without Ingress
  ports:
    - port: 80
      targetPort: 3000  # Assuming your Next.js app listens on port 3000
      protocol: TCP
    
