apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Values.serviceAccount.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceAccount.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceAccount.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: aws-load-balancer-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
