apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-api-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-api
                port:
                  number: 80
