apiVersion: v1
kind: Service
metadata:
  name: nextjs-api
  labels:
    app: nextjs-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: nextjs-api
