replicaCount: 3

image:
  repository: your-repo/nextjs-website
  tag: latest

service:
  name: nextjs-website
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: nextjs.example.com
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization:
    targetAverageUtilization: 50
vpa:
  enabled: true
  updateMode: "Auto"
networkPolicy:
  enabled: true
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "nextjs-website"
psp:
  enabled: true
  privileged: false
  allowedCapabilities:
    - NET_ADMIN
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      app: nextjs-website
grafana:
  enabled: true
  dashboard:
    enabled: true
    dashboardConfig: |
      {
        "title": "Next.js Website Dashboard",
        "panels": [
          {
            "type": "graph",
            "title": "HTTP Requests",
            "targets": [
              {
                "expr": "sum(rate(http_requests_total[5m])) by (method)",
                "legendFormat": "{{method}}"
              }
            ]
          }
        ]
      }
alertmanager:
  enabled: true
  alerts:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage for pod {{ $labels.pod }} is above 80%."
